app: 
  persistence:
    provider: 'postgres'
    endpoint: ''
    database: 'orders'
    secret:
      create: true
      name: orders-db
      username: mydbadmin
      password: kalyandb101
 
  messaging:
    provider: 'rabbitmq'
    rabbitmq:
      addresses: 
        - orders-rabbitmq.default.svc.cluster.local:5672
      secret:
        create: true
        name: orders-rabbitmq
        username: "guest"
        password: "guest"

postgresql:
  create: true
  image:
    repository: public.ecr.aws/docker/library/postgres
    pullPolicy: IfNotPresent
    tag: "16.1"
  service:
    type: ClusterIP
    port: 5432
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistentVolume:
    enabled: false
    annotations: {}
    labels: {}
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # storageClass: gp2

rabbitmq:
  create: true
  image:
    repository: "public.ecr.aws/docker/library/rabbitmq"
    pullPolicy: IfNotPresent
    tag: "3-management"
  service:
    type: ClusterIP
    amqp:
      port: 5672
    http:
      port: 15672
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistentVolume:
    enabled: false
    annotations: {}
    labels: {}
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # storageClass: gp2
