app:
  persistence:
    provider: 'redis' 
    redis:
      endpoint: ''
  endpoints:
    orders: 'http://orders.default.svc.cluster.local:80'

redis:
  create: true
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: '6.0-alpine'
  service:
    type: ClusterIP
    port: 6379

